set schema public;

drop table IF EXISTS ANIMAL;
drop table IF EXISTS PERSON;

create table PERSON (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_PERSON ON PERSON(name);

create table ANIMAL (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(100) NOT NULL,
    PERSON_ID INT
--  foreign key (PERSON_ID) references PERSON(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_ANIMAL ON ANIMAL(name, type);
